name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare Git
        run: git clone https://github.com/phoenixthrush/blocklist.git; cd blocklist
      - name: Build
        run: chmod +x ./dev.sh
      - name: Process
        run: bash ./dev.sh
      - name: Test
        run: du -hs unique.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: unique.txt
